### ISSUE TITLE
获取页面信息

### ISSUE THREAD

**Issue by PikachuWu** [qazbnm456/lulumi-browser#25]
可以获取到页面信息不？计划用这个做网页版微信多开，需要保存聊天记录

**Comment by qazbnm456** [comment]
可以利用 WebExtensions 的 API 做 script injection 以控制頁面 dom Tree，請參考 https://crxdoc-zh.appspot.com/extensions/tabs#method-executeScript。

You can use `tabs.executeScript` to manipulate the dom tree of the certain page. Please refer to https://developer.chrome.com/extensions/tabs#method-executeScript for further instruction.

**Comment by PikachuWu** [comment]
请问从哪里进行这一步骤操作呢？对于这个项目还未清楚架构，还望能够指点
微信：15220036847

**Comment by PikachuWu** [comment]
已经解决了，谢谢！
