### ISSUE TITLE
如果我想在浏览器打开的页面内加入一个js文件，应该在哪里修改？

### ISSUE THREAD

**Issue by PikachuWu** [qazbnm456/lulumi-browser#27]
能给个例子吗？谢谢！

**Comment by qazbnm456** [comment]
最簡單也最適合擴展的方法是寫一個擴充套件去控制頁面，在這邊我附上一個非常簡易的頁面腳本類擴充給您參考。

套件名稱：ContentScript Example
套件功能：載入套件後，當您只要瀏覽到網址符合 https://github.com/qazbnm456/lulumi-browser 的頁面，三秒過後會將當前頁面寫入 "ContentScript Example" 。
套件截圖：![](https://i.imgur.com/wjrueSM.png)
套件下載：
[ContentScript.zip](https://github.com/qazbnm456/lulumi-browser/files/1283737/ContentScript.zip)

**Comment by PikachuWu** [comment]
这个不错！简单！谢谢！

**Comment by qazbnm456** [comment]
@PikachuWu 不會 😃
