### ISSUE TITLE
好像页面之间cookies是分开的，但我测试一个网站的时候可能因为socket的缘故，在信息量多一点点的情况下，浏览器很容易崩溃

### ISSUE THREAD

**Issue by PikachuWu** [qazbnm456/lulumi-browser#28]
好像页面之间cookies是分开的，但我测试一个网站的时候可能因为socket的缘故，在信息量多一点点的情况下，浏览器很容易崩溃
![image](https://user-images.githubusercontent.com/13596426/30238648-4876fd10-957d-11e7-8461-b4fb29692adf.png)

**Comment by qazbnm456** [comment]
@PikachuWu 
是的，目前每個分頁都是獨自的會話。之所以會這樣做是為了讓 `chrome.webRequest` 相關事件處理器能夠帶著分頁識別 id ，但是我也發現這樣的結果並不是讓我很滿意，因為登入某網站會員過後再重開另一個同樣的分頁就會顯示未登入。我已經提交相關的 [PR](https://github.com/electron/electron/pull/10429) 給 Electron ，所以關於這個問題在 PR 合併後應該就會改善。

關於崩潰的問題，請問您方便給我更明確的資訊嗎？再請您提供給我會造成問題的擴充套件原始碼以及系統資訊（可從 about:lulumi 獲得），謝謝！

**Comment by PikachuWu** [comment]
![image](https://user-images.githubusercontent.com/13596426/30239015-cbbe6584-9585-11e7-8147-8b7bfa240537.png)
我用这个浏览器访问https://wx.qq.com，打开两个页面，然后都登陆了帐号，我在手机上通过微信，快速发送比较多的信息在已经登陆的一个帐号中，就出现了上面的状况

**Comment by qazbnm456** [comment]
@PikachuWu 不好意思，因為我沒有在使用微信，可以請您把相關的錯誤訊息貼到 https://pastebin.com/ 上讓我看看嗎？ 謝謝！

**Comment by PikachuWu** [comment]
您是指什么错误信息？

**Comment by qazbnm456** [comment]
發生錯誤時的詳細信息，再麻煩您貼給我囉，謝謝！

**Comment by PikachuWu** [comment]
明白了，您是这调试控制台的信息是吗？我已经粘贴在这里了。https://pastebin.com/7pfsmBhh

**Comment by qazbnm456** [comment]
@PikachuWu 謝謝提供，另外有辦法給出類似[這樣的錯誤訊息](https://github.com/electron/electron/pull/9494#issuecomment-302263620)給我嗎？這是 windows 給的應用程式錯誤訊息，應該在你一樓貼的那張圖片中的「查看詳細信息」裡面。

**Comment by PikachuWu** [comment]
不好意思，是因为设备本身问题导致的
