### ISSUE TITLE
请问这个项目是否不支持node版本达到v6.11.3?

### ISSUE THREAD

**Issue by PikachuWu** [qazbnm456/lulumi-browser#29]
我在新的设备上面部署的时候出现了
The engine "node" is incompatible with this module.
Expected version ">=8.1.4".
的提示

**Comment by qazbnm456** [comment]
@PikachuWu 這是因為我在這邊有限制版本號（https://github.com/qazbnm456/lulumi-browser/blob/master/package.json#L147）。

您可以選擇自行手動調整 package.json 檔，或如果您是使用 `yarn` 套件管理器，可以使用如下指令跳果檢查：`yarn --ignore-engines`。

**Comment by PikachuWu** [comment]
好的，谢谢，顺便问下，如何调整为有框窗口？

**Comment by qazbnm456** [comment]
https://github.com/qazbnm456/lulumi-browser/blob/master/src/main/index.ts#L103 ，這邊的 `frame: !isWindows` 改為 `frame:  true` 即可。

**Comment by PikachuWu** [comment]
十分感谢！

**Comment by PikachuWu** [comment]
为什么我生成之后还是无边框的呢？

**Comment by qazbnm456** [comment]
@PikachuWu 不好意思，方便截圖給我看一下嗎？

若是可以也請您先試一下把[這段](https://github.com/qazbnm456/lulumi-browser/blob/master/src/main/index.ts#L100)拿掉，我在想是不是這一行的問題！

**Comment by PikachuWu** [comment]
我直接把https://github.com/qazbnm456/lulumi-browser/blob/master/src/main/index.ts#L89L91注释掉，然后frame改为true，生成就可以了

**Comment by PikachuWu** [comment]
我直接把[这里](https://github.com/qazbnm456/lulumi-browser/blob/master/src/main/index.ts#L89L91)注释掉，然后frame改为true，生成就可以了
