### ISSUE TITLE
Can't build on OS X

### ISSUE THREAD

**Issue by matrunchyk** [qazbnm456/lulumi-browser#4]
> Building electron app(s)...
> 
> Packaging app for platform darwin x64 using electron v1.6.2
> Downloading electron-v1.6.2-linux-x64.zip
> Downloading electron-v1.6.2-mas-x64.zip
> [============================================>] 100.0% of 43.73 MB (1.11 MB/s)
> Downloading electron-v1.6.2-win32-x64.zip
> [============================================>] 100.0% of 52.33 MB (847.38 kB/s)
> Packaging app for platform win32 x64 using electron v1.6.2
> Error from `electron-packager` when building app...
> { Error: Could not find "wine" on your system.
> 
> Wine is required to use the app-copyright, app-version, build-version, icon, and
> win32metadata parameters for Windows targets.
> 
> Make sure that the "wine" executable is in your PATH.
> 
> See https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms for details.
>     at exports._errnoException (util.js:1023:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>   code: 'ENOENT',
>   errno: 'ENOENT',
>   syscall: 'spawn wine',
>   path: 'wine',
>   spawnargs:
>    [ '/Users/sergii/code/lulumi-browser/node_modules/rcedit/bin/rcedit.exe',
>      '/var/folders/5j/wj134sgd7135v9c04_9pthr00000gn/T/electron-packager/win32-x64/lulumi-browser-win32-x64/lulumi-browser.exe',
>      '--set-file-version',
>      '1.0.0',
>      '--set-product-version',
>      '1.0.0',
>      '--set-icon',
>      '/Users/sergii/code/lulumi-browser/app/icons/icon.ico' ] }
> ✨  Done in 203.98s.

Why does it ask me for wine if I want to build for macOS only? And don't care for other platforms :)

**Comment by qazbnm456** [comment]
@matrunchyk 

Hi, there. If you just want to build one for macOS only, run `yarn run build:darwin` instead.
Let me know if it works 😄

**Comment by matrunchyk** [comment]
Yeah, thanks! Works great 😃
